/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconsIconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
